[2024-04-30T10:36:38.094+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T10:36:38.240+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dog.get_dog_api scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-30T10:36:38.289+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dog.get_dog_api scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-30T10:36:38.289+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T10:36:38.351+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_dog_api> on 2024-04-02 00:00:00+00:00
[2024-04-30T10:36:38.390+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=29775) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-30T10:36:38.398+0000] {standard_task_runner.py:63} INFO - Started process 29864 to run task
[2024-04-30T10:36:38.395+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dog', 'get_dog_api', 'scheduled__2024-04-02T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/dog.py', '--cfg-path', '/tmp/tmpedx517wj']
[2024-04-30T10:36:38.403+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask get_dog_api
[2024-04-30T10:36:38.591+0000] {task_command.py:426} INFO - Running <TaskInstance: dog.get_dog_api scheduled__2024-04-02T00:00:00+00:00 [running]> on host 9822fb6f757c
[2024-04-30T10:36:38.980+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dog' AIRFLOW_CTX_TASK_ID='get_dog_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T00:00:00+00:00'
[2024-04-30T10:36:38.982+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T10:36:39.495+0000] {dog.py:15} INFO - {'message': 'https://images.dog.ceo/breeds/puggle/IMG_151824.jpg', 'status': 'success'}
[2024-04-30T10:36:39.496+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T10:36:39.496+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dog.py", line 17, in _get_dog_api
    json.dump(f, data)
  File "/usr/local/lib/python3.12/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/local/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TextIOWrapper is not JSON serializable
[2024-04-30T10:36:39.511+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dog, task_id=get_dog_api, execution_date=20240402T000000, start_date=20240430T103638, end_date=20240430T103639
[2024-04-30T10:36:39.534+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 64 for task get_dog_api (Object of type TextIOWrapper is not JSON serializable; 29864)
[2024-04-30T10:36:39.592+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-30T10:36:39.651+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T10:36:39.680+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
